### Задание 1

In [1]:
import numpy as np

In [2]:
a = np.arange(12,24)

### Задание 2

In [3]:
import math

def divisor_generator(n):
    large_divisors = []
    for i in range(1, int(math.sqrt(n) + 1)):
        if n % i == 0:
            yield i
            if i*i != n:
                large_divisors.append(n // i)
    for divisor in reversed(large_divisors):
        yield divisor

In [4]:
divs = list(divisor_generator(len(a)))
for i in range(5):
    np.reshape(a, (divs[i], divs[-(i+1)]))

### Задание 3

In [5]:
for i in range(1,4):
    np.reshape(a, (-1,i))
for i in range(1,3):
    np.reshape(a, (i, -1))

### Задание 4

In [6]:
np.reshape(a, (-1, 1)).ndim  # массив имеет ранг 2, т.е не является одномерным

2

In [61]:
b = np.random.normal(size=12).reshape(3,4)
c = b.flatten()

### Задание 6

In [66]:
a = np.arange(20,0,-2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### Задание 7

In [75]:
b = np.arange(20,0,-2).reshape(1,10)

### Задание 8

In [88]:
a = np.zeros((2,2))
b = np.ones((3,2))
c = np.concatenate((a,b), axis=0)
c.size

10

### Задание 9

In [136]:
a = np.arange(0,12)
A = a.reshape((4,3))
At = A.T
B = np.dot(A, At)
np.linalg.det(B)
# np.linalg.inv(B) невозможно, т.к матрица является вырожденной (det = 0.0)

0.0

### Задание 10

In [90]:
np.random.seed(42)

### Задание 11

In [125]:
b = np.random.normal(size=16)
b = np.array([int(el*100) for el in b])

### Задание 12

In [201]:
C = b.reshape((4,4))
D = B + (C * 10)
D_inv = np.linalg.inv(D)
print(f"det={np.linalg.det(D):.3f} rank={np.linalg.matrix_rank(D)}")
D_inv

det=104295388800.000 rank=4


array([[-2.64252335e-04,  4.57616780e-04,  1.51336125e-04,
         1.36997428e-05],
       [-3.45317856e-04, -1.67606681e-03,  9.86338909e-05,
         7.23845425e-04],
       [-1.51702949e-03, -1.02423589e-03, -1.17312665e-03,
         4.37134436e-03],
       [-5.83482038e-03, -2.58791307e-03, -6.81694971e-03,
         1.18853172e-02]])

### Задание 13

In [202]:
D_inv = np.where(D_inv < 0, D_inv, 1)
D_inv = np.where(D_inv > 0, D_inv, 0)
E = np.where(D_inv == 0, D_inv, B)
E = np.where(D_inv == 1, E, C)
E

array([[-247.,   14.,   23.,   32.],
       [  37.,  -60.,   86.,  122.],
       [ 116.,   25.,   33.,  212.],
       [ -48.,  -43.,   39.,  302.]])

In [203]:
from pprint import pprint
pprint(D_inv)
pprint(B)
pprint(C)

array([[0., 1., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])
array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])
array([[-247,  -79,   57,  -20],
       [  37,  -60,    8,  -15],
       [ 116,   25,   33,  -41],
       [ -48,  -43,   39,  -42]])
